baseURL = "https://blog.ryanc.tw/"
languageCode = "zh-TW"
title = "Ryan's blog"
author = "Ryan Chen"
theme = "hugo-clarity"
enableInlineShortcodes = true
enableEmoji = true
disqusShortname = "blog.ryanc.tw"
DefaultContentLanguage = "en"


[menus]
[[menu.main]]
name = "About"
url = "/about"

[[menu.main]]
name = "Coding"
url = "/categories/coding"

[[menu.main]]
name = "Hiking"
url = "/categories/hiking"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
enforceLightMode = true # Force the site to always load in light mode.
ga_analytics = "G-XTJ12B7L7D"

[[social]]
name = "Facebook"
url = "https://www.facebook.com/84f8dd9c9be91c9b5951"
