baseURL = "https://prpr.tw/"
languageCode = "zh-TW"
title = "Ryan's blog"
theme = "hugo_theme_pickles"

[params]
    paginate = 10
    twitter = "v_kiiii"
    github = "ryanchentw"
    author = "Ryan Chen"
    subtitle = "coding, hiking and murmurs"
    bio = "Average python programmer. Love hiking and cycling"
    ga_api_key = "UA-106885738-1"
    avatar = "https://i.imgur.com/iAhAEVA.jpg"
    disqus = "prpr-tw"

[blackfriday]
    hardLineBreak = true
    hrefTargetBlank = true

[[menu.main]]
name = "Coding"
url = "/categories/coding"

[[menu.main]]
name = "Hiking"
url = "/categories/hiking"
