baseURL = "https://prpr.tw/"
languageCode = "zh-TW"

title = "Ryan's blog"
author = "Ryan Chen"
theme = "simpleness"

enableInlineShortcodes = true
enableEmoji = true
enableDisqus = true

[params]
    paginate = 10
    twitter = "v_kiiii"
    github = "ryanchentw"
    subtitle = "coding, hiking and murmurs"
    bio = "Average python programmer. Love hiking and cycling"
    ga_api_key = "UA-106885738-1"
    avatar = "https://i.imgur.com/iAhAEVA.jpg"
    disqus = "prpr-tw"

[blackfriday]
    hardLineBreak = true
    hrefTargetBlank = true

[[menu.main]]
name = "Coding"
url = "/categories/coding"

[[menu.main]]
name = "Hiking"
url = "/categories/hiking"
